# Test Email Report Generation
# Tests for email report composition, formatting, and content generation

library(testthat)
library(blastula)

# Mock functions for testing report generation
mock_compose_email <- function(body, footer = NULL) {
  list(
    body = body,
    footer = footer,
    type = "email",
    attachments = list()
  )
}

mock_add_attachment <- function(email, file_path, filename) {
  if (!is.list(email$attachments)) {
    email$attachments <- list()
  }
  email$attachments[[filename]] <- file_path
  return(email)
}

mock_md <- function(text) {
  list(
    content = text,
    type = "markdown"
  )
}

# Test data for report generation
test_report_data <- data.frame(
  date = seq(as.Date("2024-01-01"), as.Date("2024-01-07"), by = "day"),
  weight = c(450, 455, 460, 465, 470, 475, 480),
  feed_intake = c(8.5, 8.7, 8.9, 9.1, 9.3, 9.5, 9.7),
  methane = c(200, 205, 210, 215, 220, 225, 230)
)

test_chart_types <- c("Weight Trend", "Feed Intake", "Methane Production")
test_recipient <- "user@example.com"

# Test basic email composition
test_that("compose_email creates valid email structure", {
  email_content <- "# Weekly Report\n\nThis is a test report."
  
  email <- mock_compose_email(
    body = mock_md(email_content),
    footer = mock_md("Generated by Livestock Dashboard")
  )
  
  expect_true(is.list(email))
  expect_equal(email$type, "email")
  expect_true(is.list(email$body))
  expect_true(is.list(email$footer))
  expect_true(is.list(email$attachments))
  expect_equal(email$body$content, email_content)
})

test_that("compose_email handles empty content", {
  email <- mock_compose_email(
    body = mock_md(""),
    footer = mock_md("")
  )
  
  expect_true(is.list(email))
  expect_equal(email$body$content, "")
  expect_equal(email$footer$content, "")
})

test_that("compose_email handles NULL footer", {
  email_content <- "# Report without footer"
  
  email <- mock_compose_email(
    body = mock_md(email_content),
    footer = NULL
  )
  
  expect_true(is.list(email))
  expect_equal(email$body$content, email_content)
  expect_true(is.null(email$footer))
})

# Test markdown content generation
test_that("markdown content is properly formatted", {
  # Test basic markdown
  basic_md <- "# Title\n\n**Bold text** and *italic text*"
  md_content <- mock_md(basic_md)
  
  expect_true(is.list(md_content))
  expect_equal(md_content$type, "markdown")
  expect_equal(md_content$content, basic_md)
})

test_that("markdown content handles special characters", {
  # Test special characters
  special_md <- "# Report with Special Characters\n\n- Item 1: 50% increase\n- Item 2: $100 value\n- Item 3: 25°C temperature"
  md_content <- mock_md(special_md)
  
  expect_equal(md_content$content, special_md)
  expect_true(grepl("%", md_content$content))
  expect_true(grepl("\\$", md_content$content))
  expect_true(grepl("°", md_content$content))
})

test_that("markdown content handles long text", {
  # Test long content
  long_content <- paste(rep("This is a very long line of text. ", 100), collapse = "")
  md_content <- mock_md(long_content)
  
  expect_equal(md_content$content, long_content)
  expect_true(nchar(md_content$content) > 1000)
})

# Test report content generation
test_that("report content includes summary statistics", {
  # Generate report content with summary stats
  generate_report_content <- function(data, chart_types) {
    content <- "# Livestock Dashboard Report\n\n"
    content <- paste0(content, "## Summary Statistics\n\n")
    
    # Add summary stats
    content <- paste0(content, "- **Total Records**: ", nrow(data), "\n")
    content <- paste0(content, "- **Date Range**: ", min(data$date), " to ", max(data$date), "\n")
    content <- paste0(content, "- **Average Weight**: ", round(mean(data$weight), 2), " kg\n")
    content <- paste0(content, "- **Average Feed Intake**: ", round(mean(data$feed_intake), 2), " kg/day\n")
    content <- paste0(content, "- **Average Methane**: ", round(mean(data$methane), 2), " g/day\n\n")
    
    # Add chart information
    if (length(chart_types) > 0) {
      content <- paste0(content, "## Charts Included\n\n")
      for (chart in chart_types) {
        content <- paste0(content, "- ", chart, "\n")
      }
    }
    
    return(content)
  }
  
  report_content <- generate_report_content(test_report_data, test_chart_types)
  
  expect_true(is.character(report_content))
  expect_true(grepl("Livestock Dashboard Report", report_content))
  expect_true(grepl("Summary Statistics", report_content))
  expect_true(grepl("Total Records", report_content))
  expect_true(grepl("7", report_content))  # Number of records
  expect_true(grepl("Charts Included", report_content))
  expect_true(grepl("Weight Trend", report_content))
})

test_that("report content handles empty data", {
  empty_data <- data.frame()
  
  generate_minimal_report <- function(data) {
    if (nrow(data) == 0) {
      return("# Report\n\nNo data available for the selected period.")
    }
    return("# Report\n\nData available.")
  }
  
  report_content <- generate_minimal_report(empty_data)
  
  expect_equal(report_content, "# Report\n\nNo data available for the selected period.")
})

test_that("report content handles missing columns", {
  # Data with missing columns
  incomplete_data <- data.frame(
    date = seq(as.Date("2024-01-01"), as.Date("2024-01-03"), by = "day"),
    weight = c(450, 455, 460)
    # Missing feed_intake and methane columns
  )
  
  generate_safe_report <- function(data) {
    content <- "# Report\n\n"
    
    if ("weight" %in% names(data)) {
      content <- paste0(content, "- Average Weight: ", round(mean(data$weight), 2), " kg\n")
    }
    
    if ("feed_intake" %in% names(data)) {
      content <- paste0(content, "- Average Feed Intake: ", round(mean(data$feed_intake), 2), " kg/day\n")
    } else {
      content <- paste0(content, "- Feed Intake: Data not available\n")
    }
    
    if ("methane" %in% names(data)) {
      content <- paste0(content, "- Average Methane: ", round(mean(data$methane), 2), " g/day\n")
    } else {
      content <- paste0(content, "- Methane: Data not available\n")
    }
    
    return(content)
  }
  
  report_content <- generate_safe_report(incomplete_data)
  
  expect_true(grepl("Average Weight: 455 kg", report_content))
  expect_true(grepl("Feed Intake: Data not available", report_content))
  expect_true(grepl("Methane: Data not available", report_content))
})

# Test email attachments
test_that("add_attachment adds files to email", {
  email <- mock_compose_email(
    body = mock_md("# Test Report"),
    footer = mock_md("Generated by Dashboard")
  )
  
  # Add attachment
  email <- mock_add_attachment(email, "chart1.png", "weight_trend.png")
  
  expect_true("weight_trend.png" %in% names(email$attachments))
  expect_equal(email$attachments[["weight_trend.png"]], "chart1.png")
})

test_that("add_attachment handles multiple files", {
  email <- mock_compose_email(
    body = mock_md("# Test Report"),
    footer = mock_md("Generated by Dashboard")
  )
  
  # Add multiple attachments
  email <- mock_add_attachment(email, "chart1.png", "weight_trend.png")
  email <- mock_add_attachment(email, "chart2.png", "feed_intake.png")
  email <- mock_add_attachment(email, "chart3.png", "methane_production.png")
  
  expect_equal(length(email$attachments), 3)
  expect_true("weight_trend.png" %in% names(email$attachments))
  expect_true("feed_intake.png" %in% names(email$attachments))
  expect_true("methane_production.png" %in% names(email$attachments))
})

test_that("add_attachment handles duplicate filenames", {
  email <- mock_compose_email(
    body = mock_md("# Test Report"),
    footer = mock_md("Generated by Dashboard")
  )
  
  # Add attachment with duplicate filename
  email <- mock_add_attachment(email, "chart1.png", "chart.png")
  email <- mock_add_attachment(email, "chart2.png", "chart.png")  # Same filename
  
  # Should overwrite the previous attachment
  expect_equal(length(email$attachments), 1)
  expect_equal(email$attachments[["chart.png"]], "chart2.png")
})

test_that("add_attachment handles non-existent files", {
  email <- mock_compose_email(
    body = mock_md("# Test Report"),
    footer = mock_md("Generated by Dashboard")
  )
  
  # Add attachment for non-existent file
  email <- mock_add_attachment(email, "nonexistent.png", "missing_chart.png")
  
  expect_true("missing_chart.png" %in% names(email$attachments))
  expect_equal(email$attachments[["missing_chart.png"]], "nonexistent.png")
})

# Test email subject generation
test_that("email subject includes date", {
  generate_subject <- function(frequency, date = Sys.Date()) {
    return(paste("Livestock Dashboard", frequency, "Report -", date))
  }
  
  subject <- generate_subject("Weekly")
  expect_true(grepl("Livestock Dashboard", subject))
  expect_true(grepl("Weekly", subject))
  expect_true(grepl("Report", subject))
  expect_true(grepl(as.character(Sys.Date()), subject))
})

test_that("email subject handles different frequencies", {
  frequencies <- c("Daily", "Weekly", "Monthly")
  
  for (freq in frequencies) {
    subject <- paste("Livestock Dashboard", freq, "Report -", Sys.Date())
    expect_true(grepl(freq, subject))
  }
})

test_that("email subject handles custom dates", {
  custom_date <- as.Date("2024-01-15")
  subject <- paste("Livestock Dashboard Weekly Report -", custom_date)
  
  expect_true(grepl("2024-01-15", subject))
})

# Test email recipient validation
test_that("email recipient validation works", {
  validate_recipient <- function(email) {
    if (is.null(email) || !is.character(email) || length(email) != 1) {
      return(FALSE)
    }
    if (email == "" || !grepl("^[^@]+@[^@]+\\.[^@]+$", email)) {
      return(FALSE)
    }
    return(TRUE)
  }
  
  # Valid emails
  valid_emails <- c(
    "user@example.com",
    "test.user@domain.co.uk",
    "user+tag@example.org"
  )
  
  for (email in valid_emails) {
    expect_true(validate_recipient(email))
  }
  
  # Invalid emails
  invalid_emails <- c(
    "invalid-email",
    "@example.com",
    "test@",
    ""
  )
  
  for (email in invalid_emails) {
    expect_false(validate_recipient(email))
  }
  
  # Test vector input separately
  expect_false(validate_recipient(c("user1@example.com", "user2@example.com")))
  
  # Test NULL separately
  expect_false(validate_recipient(NULL))
})

# Test report frequency validation
test_that("report frequency validation works", {
  validate_frequency <- function(freq) {
    valid_frequencies <- c("Daily", "Weekly", "Monthly")
    return(freq %in% valid_frequencies)
  }
  
  # Valid frequencies
  valid_freqs <- c("Daily", "Weekly", "Monthly")
  for (freq in valid_freqs) {
    expect_true(validate_frequency(freq))
  }
  
  # Invalid frequencies
  invalid_freqs <- c("Yearly", "Hourly", "Custom", "", NULL)
  for (freq in invalid_freqs) {
    expect_false(validate_frequency(freq))
  }
})

# Test complete email report workflow
test_that("complete email report workflow works", {
  # Mock the complete workflow
  generate_complete_report <- function(data, recipient, frequency, chart_types) {
    # Generate content
    content <- "# Livestock Dashboard Report\n\n"
    content <- paste0(content, "## Summary\n\n")
    content <- paste0(content, "- Records: ", nrow(data), "\n")
    content <- paste0(content, "- Date Range: ", min(data$date), " to ", max(data$date), "\n")
    
    # Create email
    email <- mock_compose_email(
      body = mock_md(content),
      footer = mock_md("Generated by Livestock Dashboard")
    )
    
    # Add chart attachments
    for (chart_type in chart_types) {
      filename <- paste0(gsub(" ", "_", tolower(chart_type)), ".png")
      email <- mock_add_attachment(email, paste0("temp_", filename), filename)
    }
    
    # Generate subject
    subject <- paste("Livestock Dashboard", frequency, "Report -", Sys.Date())
    
    return(list(
      email = email,
      subject = subject,
      recipient = recipient
    ))
  }
  
  result <- generate_complete_report(test_report_data, test_recipient, "Weekly", test_chart_types)
  
  expect_true(is.list(result))
  expect_true(is.list(result$email))
  expect_true(is.character(result$subject))
  expect_equal(result$recipient, test_recipient)
  expect_equal(length(result$email$attachments), length(test_chart_types))
  expect_true(grepl("Weekly", result$subject))
})

# Test error handling in report generation
test_that("report generation handles data errors gracefully", {
  # Test with corrupted data
  corrupted_data <- data.frame(
    date = c("invalid_date", "2024-01-02", "2024-01-03"),
    weight = c("not_a_number", 455, 460)
  )
  
  safe_report_generation <- function(data) {
    tryCatch({
      content <- "# Report\n\n"
      
      # Try to process dates
      if ("date" %in% names(data)) {
        valid_dates <- tryCatch({
          suppressWarnings(as.Date(data$date))
        }, error = function(e) {
          return(NA)
        })
        
        if (!all(is.na(valid_dates))) {
          content <- paste0(content, "- Valid dates: ", sum(!is.na(valid_dates)), "\n")
        } else {
          content <- paste0(content, "- Date processing failed\n")
        }
      }
      
      # Try to process numeric data
      if ("weight" %in% names(data)) {
        numeric_weights <- tryCatch({
          suppressWarnings(as.numeric(data$weight))
        }, error = function(e) {
          return(NA)
        })
        
        if (!all(is.na(numeric_weights))) {
          content <- paste0(content, "- Valid weights: ", sum(!is.na(numeric_weights)), "\n")
        } else {
          content <- paste0(content, "- Weight processing failed\n")
        }
      }
      
      return(content)
    }, error = function(e) {
      return("# Report\n\nError generating report: Unable to process data")
    })
  }
  
  result <- safe_report_generation(corrupted_data)
  
  expect_true(is.character(result))
  expect_true(grepl("Report", result))
  expect_false(grepl("Error generating report", result))
})

# Test report content formatting
test_that("report content formatting handles special cases", {
  # Test with very small numbers
  small_data <- data.frame(
    date = as.Date("2024-01-01"),
    weight = 0.001,
    feed_intake = 0.0001
  )
  
  format_numbers <- function(data) {
    content <- "# Report\n\n"
    content <- paste0(content, "- Weight: ", sprintf("%.6f", mean(data$weight)), " kg\n")
    content <- paste0(content, "- Feed Intake: ", sprintf("%.6f", mean(data$feed_intake)), " kg/day\n")
    return(content)
  }
  
  result <- format_numbers(small_data)
  
  expect_true(grepl("0.001000", result))
  expect_true(grepl("0.000100", result))
})

test_that("report content formatting handles large numbers", {
  # Test with very large numbers
  large_data <- data.frame(
    date = as.Date("2024-01-01"),
    weight = 1000000,
    feed_intake = 500000
  )
  
  format_large_numbers <- function(data) {
    content <- "# Report\n\n"
    content <- paste0(content, "- Weight: ", format(mean(data$weight), big.mark = ",", scientific = FALSE), " kg\n")
    content <- paste0(content, "- Feed Intake: ", format(mean(data$feed_intake), big.mark = ",", scientific = FALSE), " kg/day\n")
    return(content)
  }
  
  result <- format_large_numbers(large_data)
  
  expect_true(grepl("1,000,000", result))
  expect_true(grepl("500,000", result))
})

# Test report content with missing values
test_that("report content handles missing values", {
  # Data with missing values
  data_with_na <- data.frame(
    date = seq(as.Date("2024-01-01"), as.Date("2024-01-05"), by = "day"),
    weight = c(450, NA, 460, 465, NA),
    feed_intake = c(8.5, 8.7, NA, 9.1, 9.3)
  )
  
  handle_missing_values <- function(data) {
    content <- "# Report\n\n"
    
    # Handle missing weights
    if ("weight" %in% names(data)) {
      valid_weights <- data$weight[!is.na(data$weight)]
      if (length(valid_weights) > 0) {
        content <- paste0(content, "- Average Weight: ", round(mean(valid_weights), 2), " kg (", length(valid_weights), " valid records)\n")
      } else {
        content <- paste0(content, "- Weight: No valid data\n")
      }
    }
    
    # Handle missing feed intake
    if ("feed_intake" %in% names(data)) {
      valid_feed <- data$feed_intake[!is.na(data$feed_intake)]
      if (length(valid_feed) > 0) {
        content <- paste0(content, "- Average Feed Intake: ", round(mean(valid_feed), 2), " kg/day (", length(valid_feed), " valid records)\n")
      } else {
        content <- paste0(content, "- Feed Intake: No valid data\n")
      }
    }
    
    return(content)
  }
  
  result <- handle_missing_values(data_with_na)
  
  expect_true(grepl("Average Weight: 458.33 kg \\(3 valid records\\)", result))
  expect_true(grepl("Average Feed Intake: 8.9 kg/day \\(4 valid records\\)", result))
})
